name: Process Scheduled Issues

on:
  issues:
    types: [opened]

jobs:
  process-scheduled-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm install
